# Generated by Django 4.2.2 on 2023-06-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company_details',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=100)),
                ('TradingCode', models.CharField(max_length=50)),
                ('ScripCode', models.CharField(max_length=5)),
                ('Sector', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='company_other_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('TradingCode', models.CharField(max_length=50)),
                ('Date', models.CharField(max_length=30)),
                ('SponsorDirector', models.FloatField()),
                ('Govt', models.FloatField()),
                ('Institute', models.FloatField()),
                ('ForeignNum', models.FloatField()),
                ('Public', models.FloatField()),
            ],
        ),
    ]
